mvcproje/Models/ErrorViewModel.cs
namespace mvcproje.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

mvcproje/Models/Kadro.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mvcproje.Models
{
    public class Kadro
    {
        public int Id {get;set;}
        public string name {get;set;}
        public string position {get;set;}
        public  string Image {get; set;}
        public string nationality{get;set;}
    }
}

mvcproje/Models/Repository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mvcproje.Models
{
    public class Repository
    {
        public static List<Kadro> Kadros {get;set;} = new List<Kadro>(){
            new Kadro(){
                Id = 1,
                name = "Fernando Muslera",
                position = "kaleci",
                nationality = "Uruguay",
                Image = "https://hlkiurt3.rocketcdn.com/profiles/b13b9abd2c5e41a1a6d69d21e2bb2cce.jpeg"
            },
            new Kadro(){
                Id = 2,
                name = "Davinson Sanchez",
                position = "defans",
                nationality = "Kolombiya",
                Image = "https://hlkiurt3.rocketcdn.com/profiles/8f0e1ac29bcb4a17a2c4c17a652c8fc2.jpeg"
            },
            new Kadro(){
                Id = 3,
                name = "Abdülkerim Bardakci",
                position = "defans",
                nationality = "Türkiye",
                Image = "https://hlkiurt3.rocketcdn.com/profiles/9bc566724a734fee8d3acef1b3cd09b5.jpeg"
            }
        };
        public static Kadro GetKadroById(int id)
        {
            return Kadros.FirstOrDefault(u => u.Id == id);
        }
    }
}

mvcproje/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using mvcproje.Models;

namespace mvcproje.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

mvcproje/Controllers/KadroController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvcproje.Models;

namespace mvcproje.Controllers
{

    public class KadroController : Controller
    {


        public IActionResult Index()
        {
            return View(Repository.Kadros);
        }
        public IActionResult Info(int id)
        {

            return View(Repository.GetKadroById(id));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

mvcproje/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

mvcproje/Views/Kadro/Index.cshtml
@model List<Kadro>

<h1>Futbolcu Kadrosu</h1>
<div class="row">
    
        @foreach(var item in Model){
            <div class="col-md-4">
                @await Html.PartialAsync("_Card",item)
            </div>
            
        }
    
</div>

mvcproje/Views/Kadro/Info.cshtml
@model Kadro


<div  class="card" style="width: 18rem;">

    <img src="@Model.Image" class="card-img-top" alt="...">
    <div class="card-body">
        <a asp-controller="Kadro" asp-action="Info" asp-route-id="@Model.Id">
            <h5 class="card-title">@Model.name</h5>
        </a>
      <p class="card-text">@Model.nationality</p>
      <p class="card-text">@Model.position</p>
    </div>
  </div>

mvcproje/Views/Shared/_Card.cshtml
@model Kadro

<div  class="card row" style="width: 18rem;">

    <img src="@Model.Image" class="card-img-top" alt="...">
    <div class="card-body">
        <a asp-controller="Kadro" asp-action="Info" asp-route-id="@Model.Id">
            <h5 class="card-title">@Model.name</h5>
        </a>
      
      <p class="card-text">@Model.position</p>
    </div>
  </div>

mvcproje/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvcproje</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvcproje.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @await Html.PartialAsync("_Navbar")
        @RenderSection("Header",false)
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - mvcproje - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

mvcproje/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-dark navbar-expand-lg bg-danger mb-5">
    <div class="container">
      <a class="navbar-brand" href="#">502</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a asp-con class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-controller="Kadro" asp-action="Index">Kadro</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>